### ISSUE TITLE
Allow self signed certificate when request openapi json from website

### ISSUE THREAD

**Issue by jackykwan-eventx** [Redocly/redocly-cli#1017]
**Is your feature request related to a problem? Please describe.**

When i use `redoc-cli` to `build`, i can't generate html with url under self signed cert
```bash
npx redoc-cli build  URL_WITH_SELF_SIGNED_CERT
```

This is the error message
```
Error: request to `URL_WITH_SELF_SIGNED_CERT` failed, reason: self signed certificate
    at BaseResolver.<anonymous> (/home/user/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:117:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/user/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Describe the solution you'd like**

simular to `curl`, a `-k` or `--insecure` options allow to bypass the cert check will be great

**Comment by lornajane** [comment]
Thanks @jackykwan-eventx , this is a good suggestion.

**Comment by drwpow** [comment]
Perhaps this could be an option [in the per-API configuration](https://redocly.com/docs/cli/configuration/apis/)?
