### ISSUE TITLE
require() of ES Module `node-fetch/src/index.js` from `@redocly/cli/lib/fetch-with-timeout.js` not supported.

### ISSUE THREAD

**Issue by Laurensdc** [Redocly/redocly-cli#1312]
**Describe the bug**
The `build-docs` command fails on v1.3.0 where it works fine on 1.2.0.

**To Reproduce**
```shell
npx @redocly/cli@1.3.0 build-docs openapi.yaml
/Users/.../node_modules/@redocly/cli/lib/fetch-with-timeout.js:12
const node_fetch_1 = require("node-fetch");
                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/.../node_modules/node-fetch/src/index.js from /Users/.../node_modules/@redocly/cli/lib/fetch-with-timeout.js not supported.
Instead change the require of index.js in /Users/.../node_modules/@redocly/cli/lib/fetch-with-timeout.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/.../node_modules/@redocly/cli/lib/fetch-with-timeout.js:12:22)
    at Object.<anonymous> (/Users/.../node_modules/@redocly/cli/lib/utils.js:24:30)
    at Object.<anonymous> (/Users/.../node_modules/@redocly/cli/lib/commands/preview-docs/index.js:16:17)
    at Object.<anonymous> (/Users/.../node_modules/@redocly/cli/lib/index.js:17:24)
    at Object.<anonymous> (/Users/.../node_modules/@redocly/cli/bin/cli.js:3:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.2
 ✘  ~/code/...   ci/CRP-8-api-docs ±  npx @redocly/cli@1.2.0 build-docs openapi.yaml
Need to install the following packages:
@redocly/cli@1.2.0
Ok to proceed? (y) y

    ╔══════════════════════════════════════════════════════╗
    ║                                                      ║
    ║  A new version of Redocly CLI (1.3.0) is available.  ║
    ║  Update now: `npm i -g @redocly/cli@latest`.         ║
    ║  Changelog: https://redocly.com/docs/cli/changelog/  ║
    ║                                                      ║
    ╚══════════════════════════════════════════════════════╝
  Found undefined and using theme.openapi options
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
Prerendering docs

🎉 bundled successfully in: redoc-static.html (230 KiB) [⏱ 1ms].
```

**Expected behavior**

It should work on v1.3.0 as it does on 1.2.0

**OpenAPI description**

Swagger v2.0.0

**Redocly Version(s)**
1.3.0

**`Node.js` Version(s)**
18.18.2

**Additional context**
Same behavior with the installed version in devDependencies.

Obfuscated the absolute directories in this issue report.
 I manually added the `...` after `/Users/` in all paths, it's not direct CLI output.

**Comment by tatomyr** [comment]
Do you by chance have installed `node-fetch` in the same project? If yes, which version is it?
Note: I believe there is a related bug already: https://github.com/Redocly/redocly-cli/issues/1260

**Comment by tatomyr** [comment]
Hey @Laurensdc, Could you check if this is still an issue in v1.4.1?

**Comment by tatomyr** [comment]
I'm closing this. Feel free to tag me if you think it's not resolved.
