### ISSUE TITLE
Upgraded to Redocly 1.6.0 and now getting errors related to wrap-ansi

### ISSUE THREAD

**Issue by monica-m-ps** [Redocly/redocly-cli#1378]
**Describe the bug**

I recently upgraded Docusaurus 3.0.0 and Redocly to 1.6.0. It didn't work and throws some mysterious errors.
I'm using Node 19.3.0.

**To Reproduce**

Upgrade Docusaurus dependencies.
Upgrade Redocly.
Run yarn run build.

**Expected behavior**

Should build with no errors.
**Logs**

```
/Users/monica.manghnani/Dojo-Payments/remote-payments-version-2/docs-site/node_modules/@redocly/cli/node_modules/cliui/build/index.cjs:293
const wrap = require('wrap-ansi');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/monica.manghnani/Dojo-Payments/remote-payments-version-2/docs-site/node_modules/wrap-ansi/index.js from /Users/monica.manghnani/Dojo-Payments/remote-payments-version-2/docs-site/node_modules/@redocly/cli/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /Users/monica.manghnani/Dojo-Payments/remote-payments-version-2/docs-site/node_modules/@redocly/cli/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/monica.manghnani/Dojo-Payments/remote-payments-version-2/docs-site/node_modules/@redocly/cli/node_modules/cliui/build/index.cjs:293:14)
    at Object.<anonymous> (/Users/monica.manghnani/Dojo-Payments/remote-payments-version-2/docs-site/node_modules/@redocly/cli/node_modules/yargs/build/index.cjs:1:54333)
    at Object.<anonymous> (/Users/monica.manghnani/Dojo-Payments/remote-payments-version-2/docs-site/node_modules/@redocly/cli/node_modules/yargs/index.cjs:5:30)
    at Object.<anonymous> (/Users/monica.manghnani/Dojo-Payments/remote-payments-version-2/docs-site/node_modules/@redocly/cli/lib/index.js:14:15)
    at Object.<anonymous> (/Users/monica.manghnani/Dojo-Payments/remote-payments-version-2/docs-site/node_modules/@redocly/cli/bin/cli.js:3:1) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by tatomyr** [comment]
Hi @monica-m-ps, 

The error seems to be related to something using ES Modules, while Redocly CLI uses CommonJS. However, from the context it's unclear what could cause the error since there were no recent changes related to that matter. What version have you upgraded from? Does the error disappear if you downgrade it back?

**Comment by monica-m-ps** [comment]
Hello @tatomyr. With the latest Docusaurus update, this problem might occur for some users. 
A quick tip to fix it.
https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#mdx-plugins.

Or updating yarn to a stable version should help. This fixed the error for me.
Thank you!

Closing this issue.

**Comment by lornajane** [comment]
Thanks for the update and the link @monica-m-ps !
