### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by felipeloha** [Redocly/redocly-cli#799]
**Describe the bug**
RangeError: Maximum call stack size exceeded when a recursion is present in the spec

**To Reproduce**
1. Given a yml file that references itself
2. run `redocly preview-docs`
3. the error 
```RangeError: Maximum call stack size exceeded
    at tn (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:647081)
    at new Nc (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:39:68016)
    at https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:39:65200
    at Array.map (<anonymous>)
    at Pc (https://cdn.redoc.ly/r```

**Expected behavior**
The docs are rendered properly

**Logs**
```RangeError: Maximum call stack size exceeded
    at tn (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:647081)
    at new Nc (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:39:68016)
    at https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:39:65200
    at Array.map (<anonymous>)
    at Pc (https://cdn.redoc.ly/r```

**OpenAPI definition**
"openapi": "3.0.0",

**Redocly Version(s)**
1.0.0-beta.105

**`Node.js` Version(s)**
18.2.0

**Comment by felipeloha** [comment]
sample file: [sample.json.zip](https://github.com/Redocly/redocly-cli/files/9288277/sample.json.zip)

**Comment by tatomyr** [comment]
Hi @felipeloha, 

Could you check the sample file? I tried to run the command with it and cannot reproduce your case.

**Comment by felipeloha** [comment]
it breaks on my machine
here attached the command with the version and the result on the browser

![Screenshot 2022-08-09 at 11 56 39](https://user-images.githubusercontent.com/36071293/183620812-c2f7d641-87da-496b-b19d-1c20f1634ce1.png)
![Screenshot 2022-08-09 at 11 57 37](https://user-images.githubusercontent.com/36071293/183620950-fa65c278-918b-4ac4-8197-2e1555b07bfa.png)

**Comment by tatomyr** [comment]
Ah, I see. This must be a [Redoc](https://github.com/Redocly/redoc) issue, most likely related to [this one](https://github.com/Redocly/redoc/issues/2114).

**Comment by felipeloha** [comment]
yes i was thinking the same

**Comment by tatomyr** [comment]
I'm closing the issue since it should be resolved on Redoc's side. No need to update anything in Redocly CLI.
Should it not get resolved, feel free to reopen the issue.

**Comment by felipeloha** [comment]
@tatomyr 
I dont understand the relation between the versions of redoc and redocly.
which redocly cli version should I use to have https://github.com/Redocly/redoc/issues/2114 fixed?

**Comment by tatomyr** [comment]
Hi @felipeloha,

Redocly CLI uses the latest version of Redoc. The reason it doesn't get fixed for you might be some caching. Could you check this in the incognito mode?

**Comment by felipeloha** [comment]
@tatomyr I didnt know if we had to update the cli. we tried it out and everything is working. thanks
